[package]
name = "project_euler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.3"
lazy_static = "1.4"
fibonacci = { path = "fibonacci" }
primes = { path = "primes" }
